=== muggezifter/portefeuille-cms/httpdocs/data/Loopkevertabel.dtd
<!ELEMENT loopkevertabel (table+) >
<!ELEMENT table (choice+) >
<!ATTLIST table id ID  #REQUIRED >
<!ATTLIST table name CDATA  #REQUIRED >
<!ELEMENT choice (option+) >
<!ATTLIST choice id ID  #REQUIRED>
<!ELEMENT option (criterion,(family|subfamily)?,(target|species)) >
<!ELEMENT criterion (#PCDATA) >
<!ELEMENT family (#PCDATA) >
<!ELEMENT subfamily (#PCDATA) >
<!ELEMENT target EMPTY >
<!ATTLIST target id IDREF  #REQUIRED >
<!ELEMENT species (#PCDATA) >
<!ATTLIST species id ID  #REQUIRED >

=== muggezifter/portefeuille-cms/data/Loopkevertabel.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE loopkevertabel SYSTEM "Loopkevertabel.dtd">
<loopkevertabel>
  <table id="S" name="sleuteltabel">
    <choice id="S1">
      <option>
        <criterion>
          <![CDATA[Sprieten op de zijkant van het voorhoofd ingeplant. Grote, scherp getande voorkaken, 
  <a onclick="showImage(41)">fig. 41</a>. Vliegt overdag.]]>
        </criterion>  
        <family>FAMILIE CICINDELIDAE</family>
        <target id="A1" />
      </option>
      <option>
        <criterion>
          <![CDATA[Sprieten onder de zijkant van het voorhoofd, aan de basis van de bovenkaken ingeplant,
  <a onclick="showImage(40)">fig. 40</a>, zelden overdag vliegend.]]>
        </criterion>
        <family>FAMILIE CARABIDAE</family>
        <target id="S2" />
      </option>
    </choice>
    <choice id="S2">
      <option>
        <criterion>
          <![CDATA[Het uiteinde der voorschenen met een diepe uitholling aan de binnenzijde, fig. 12a.]]>
        </criterion>
        <target id="S3" />
      </option>
      <option>
        <criterion>
          <![CDATA[Het uiteinde der voorschenen zonder een dergelijke uitholling, fig. 12b.]]>
        </criterion>
        <subfamily>CARABINAE</subfamily>
        <target id="B1" />
      </option>
    </choice>
    <choice id="S3">
      <option>
        <criterion>
          <![CDATA[Tweede t.m. zesde sprietlid met lange, afstaande haren bezet; eerste lid sterk verdikt,
  bijna even groot als de drie volgende leedjes samen, fig. 1.]]>
        </criterion>
        <subfamily>CARABINAE</subfamily>
        <target id="B1" />
      </option>
      <option>
        <criterion>
          <![CDATA[Uitpüilende ogen, evenwijdige zijden, grote langwerpige "spiegels" op de deksch., kor-
  te pootjes, bronskleurig, 6 mm of kleiner, fig. 18.]]>
        </criterion>
        <subfamily>CARABINAE</subfamily>
        <target id="B1" />  
      </option>
      <option>
        <criterion>
          <![CDATA[Voorpoten tot graafpoten vervormd, fig. 11a en 11b.]]>
        </criterion>
        <subfamily>CARABINAE</subfamily>
          <target id="B1" />  
      </option>
      <option>
        <criterion>
          <![CDATA[Niet aldus.]]>
        </criterion>
        <subfamily>HARPALINAE</subfamily>
        <target id="S4" />  
      </option>
    </choice>
    <choice id="S4">
      <option>
        <criterion>
          <![CDATA[Zijgroef van de bovenkaken met een borstelhaar, fig. 40. Op enkele soorten na kleiner
dan 5 mm. tabel]]>
        </criterion>
        <target id="C1" />
      </option>
      <option>
        <criterion>
          <![CDATA[Zijgroef van de bovenkaken zonder borstelhaar.]]>
        </criterion>
        <target id="S5" />
      </option>
    </choice>
    <choice id="S5">
      <option>
        <criterion>
          <![CDATA[Deksch. afgeknot, het achterlijf niet volkomen bedekkend, fig. 20. (bij Masoreus niet
duidelijk; zie ook bij Brachynus, tabel C)]]>
        </criterion>
        <target id="F1" />
      </option>
      <option>
        <criterion>
          <![CDATA[Deksch. onverkort]]>
        </criterion>
        <target id="S6" />
      </option>
    </choice>
    <choice id="S6">
      <option>
        <criterion>
          <![CDATA[Voorhoofd aan weerskanten met tweehaarstippen tegen de oogrand, fig. 42. (kever scheef
van boven en van opzij goed bekijken!) ]]>
        </criterion>
        <target id="D1" />
      </option>
      <option>
        <criterion>
          <![CDATA[Voorhoofd aan weerskanten met één haarstip tegen de oogrand, fig. 43.]]>
        </criterion>
        <target id="E1" />
      </option>
    </choice>
  </table>
  <table id="A" name="FAM. CICINDELIDAE">
    <choice id="A1">
      <option>
        <criterion>
          <![CDATA[Deksch. groen met enkele wit-gele vlekjes, de middelste soms een band vormend. 12-
15 mm, alg., op diluviale zandgrond op heidevelden en zandwegen. IV-VI]]>
        </criterion>
        <species id="A1-1">
          <![CDATA[CICINDELA CAMPESTRIS L.]]>
        </species>
      </option>
      <option>
        <criterion>
          <![CDATA[Deksch. bronskl. zwart - bruin bronskl. met witgele dwarsband en vlekken]]>
        </criterion>
        <target id="A2"/>
      </option>
    </choice>
    <choice id="A2">
      <option>
        <criterion>
          <![CDATA[Bovenlip geheel zwart, fig.41. Deksch. bronskl. zwart, met zijdeglans. Deksch. zeer
duidelijk gekorreld, met ondiepe stippen. De a. hoeken der deksch. nooit geel. Dijen
blauw. 15-17 mm, alg., op diluvium in heidestreken, vooral op zandwegen en bij
voorkeur in dennebossen.]]>
        </criterion>
          <species id="A2-1">
          <![CDATA[CICINDELA SILVATICA L.]]>
        </species>
      </option>
      <option>
        <criterion>
          <![CDATA[Bovenlip geelwit. Deksch. bruin bronskl. met gele achterhoeken, fig. 27]]>
        </criterion>
        <target id="A3"/>
      </option>
    </choice>
    <choice id="A3">
      <option>
        <criterion>
          <![CDATA[De middenband der deksch. is rechthoekig naar achteren uitgetrokken. Het voorhoofd
is achter de ogen met witte haren bezet. Fig. 28. 12-16 min, z-11g., op de laatste duinen- 
rij en op het strand, vooral op de Waddeneilamden, V-VIII.]]>
        </criterion>
        <species id="A3-1">
          <![CDATA[CICINDELA MARITIMA LATR.
(Op het zgn. groene strand van Voorne is CICINDELA TRISIGNATA LATR. waargenomen)]]>
        </species>
      </option>
      <option>
        <criterion>
          <![CDATA[Middenband der deksch. als in fig. 27, 12-16 mm, z. a., in droge zandige streken.]]>
        </criterion>
        <species id="A3-2">
          <![CDATA[CICINDELA HYBRIDA L.]]>
        </species>
      </option>
    </choice>  
  </table>
  <table id="B" name="FAM. CARABIDAE, SUBFAM. CARABINAE">
    <choice id="B1">
      <option>
        <criterion>
            <![CDATA[Schijfvormig lichaam. Deksch. okergeel met groene vlekken of dwarsbanden, fig. 19,
S-6 mm, op sommige plaatsen n. z., op zandige oevers, meestal ingegraven, soms in
aantal bijeen. V-X. ]]></criterion>
          <species id="B1-1"><![CDATA[OMOPI-IRON LINEBATUS F]]></species>
      </option>
        <option>
        <criterion>Anders</criterion>
            <target id="B2" />
        </option>  
    </choice>
    <choice id="B2">
          <option>
              <criterion>
                  <![CDATA[Deksch. met oogstippen, fig. 29, of grote stippen. Groter dan 6 mm. Matig tot sterk uit-
puilende ogen]]></criterion>
              <target id="B3" />
          </option>
          <option>
              <criterion></criterion>
              <target id="B6" />
          </option>
      </choice>
      <choice id="B3">
       <option>
              <criterion>
                  <![CDATA[De tweede tussenr. der deksch. met 4-5 grote, diepe stippen; in de vierde tussenr. 2-3
van dergelijke stippen. Donker bronskl. bruin met metaalkl. zijrand aan halssch. en dek-
sch. 11-13 mm, t. z., langs oevers en in vochtige weilanden .]]>
              </criterion>
              <species id="B3-1"><![CDATA[BLETHISA MULTIPUNCTATA L.]]></species>
          </option>
          <option>
              <criterion><![CDATA[Deksch. met oogstippen. Kleine]]></criterion>
              <target id="B4" />
          </option>
      </choice>
      <choice id="B4">
       <option>
              <criterion><![CDATA[Oogstippen omwald]]></criterion>
                <target id="B5" />
          </option>
          <option>
              <criterion></criterion>
              <target id="" />
          </option>
      </choice>
      <choice id="B5">
       <option>
              <criterion></criterion>
              <species id=""></species>
          </option>
          <option>
              <criterion></criterion>
              <target id="" />
          </option>
      </choice>
  </table>
  <table id="C" name="">
    <choice id="C1">
      <option>
        <criterion></criterion>
          <species id="C1-1"></species>
      </option>
    </choice>
  </table>
  <table id="D" name="">
    <choice id="D1">
      <option>
        <criterion></criterion>
          <species id="D1-1"></species>
      </option>
    </choice>
  </table>
  <table id="E" name="">
    <choice id="E1">
      <option>
        <criterion></criterion>
          <species id="E1-1"></species>
      </option>
    </choice>
  </table>
  <table id="F" name="">
    <choice id="F1">
      <option>
        <criterion></criterion>
          <species id="F1-1"></species>
      </option>
    </choice>
  </table>
</loopkevertabel>
